# Dir["/Users/tnunes/development/xpair/mixins/*.rb"].each {|file| require file }
# Dir["/Users/tnunes/development/xpair/model/*.rb"].each {|file| require file }
# Dir["/Users/tnunes/development/xpair/adapters/rdf/*.rb"].each {|file| require file }
require 'set'
require 'forwardable'
require 'mixins/graph_converter'
require 'mixins/operation_factory'
require 'mixins/config.rb'
require 'mixins/writable.rb'
require 'mixins/readable.rb'
require 'execution/workflow.rb'


require 'mixins/enumerable'
require 'mixins/relation'
require 'exceptions/missing_relation_exception'
require 'exceptions/missing_value_exception'
require 'exceptions/invalid_input_exception'
require 'exceptions/disconnected_operation_exception'
require 'exceptions/missing_auxiliary_function_exception'
require 'exceptions/numeric_item_required_exception'

require 'model/node'
require 'model/edge'
require 'model/entity'
require 'model/type'
require 'model/literal'
require 'model/schema_relation'
require 'model/computed_relation'
require 'model/path_relation'
require 'model/namespace'
require 'model/result_set'
require 'model/relation_handler'

require 'mixins/model_factory'
require 'adapters/navigational'
require 'adapters/searchable'
require 'adapters/data_server'
require 'adapters/rdf/rdf_navigational'
require 'adapters/rdf/sparql_helper'
require 'adapters/rdf/rdf_data_server'
require 'adapters/rdf/blazegraph_data_server'
require 'adapters/memory/memory_repository'
require 'visualization/visualization'
require 'securerandom'
require 'operations/auxiliary_function'
require 'operations/operation'
require 'operations/set_operation'

require 'operations/pivot'

require 'operations/group'
require 'operations/grouping_relations/grouping_relation'
require 'operations/grouping_relations/by_image'

require 'operations/map'
require 'operations/mapping_functions/avg'
require 'operations/mapping_functions/count'
require 'operations/mapping_functions/sum'

require 'operations/filters/filter_factory'
require 'operations/refine'
require 'operations/pivot'
require 'operations/filters/filter'
require 'operations/filters/simple_filter'
require 'operations/filters/composite_filter'
require 'operations/filters/and'
require 'operations/filters/or'
require 'operations/filters/equals'
require 'operations/filters/equals_one'
require 'operations/filters/contains'
require 'operations/filters/match'
require 'operations/filters/greater_than'
require 'operations/filters/greater_than_equal'
require 'operations/filters/less_than_equal'
require 'operations/filters/less_than'
require 'operations/filters/not'
require 'operations/filters/c_filter'
require 'operations/filters/in_memory_filter_interpreter'
require 'adapters/rdf/filter_interpreter'
require 'operations/keyword_search'
require 'operations/nodes_select'
require 'operations/unite'
require 'operations/intersect'
require 'operations/diff'